### ISSUE TITLE
Průběh schůzky 21/3

### ISSUE THREAD

**Issue by hoanghun** [hoanghun/ZSWI#24]
Někdo napište, co se probíralo na schůzce, ať vím, co dodělat :) Klidně proto udělejte novou stránku na WIKI :dagger:

**Comment by simeckol** [comment]
Je nutný trošku předělat specifikaci, tzn.:

- odstranit všechny podmiňovací výrazy a nahradit je určitými (by měl fungovat -> bude fungovat, problém by neměl být -> nebude problém, ...)
- slovníček nebude potřeba -> smazat
- seznam úkolů taky smazat, od toho máme _Issues_
- ve _Kvalitativních parametrech_ nepsat o GUI, od toho máme sekci _Uživatelská rozhraní_

- další ještě doplním za chvilku :)

**Comment by hoanghun** [comment]
Kdo udělá Ganttův diagram? :dancing_men:

**Comment by simeckol** [comment]
klidně ten diagram jako takový udělám, ale někdo musí vymyslet jeho obsah :D
