### ISSUE TITLE
Vytvořit UML

### ISSUE THREAD

**Issue by simeckol** [hoanghun/ZSWI#25]
po důkladné analýze

**Comment by hoanghun** [comment]
Přečtěte si konec bakalářky Vaška => [bakalarka](https://portal.zcu.cz/portal/studium/prohlizeni.html?pc_pagenavigationalstate=H4sIAAAAAAAAAGNgYGBkYDM1tDA3MhZmZADxOIpLEktSvVMrwTwRXUsjI2NjcyMDYzMLUxNzcwMzc0ugDAMAIOZSsToAAAA*#prohlizeniSearchResult)
