### ISSUE TITLE
Vytvořit Ganttův diagram

### ISSUE THREAD

**Issue by simeckol** [hoanghun/ZSWI#27]

**Comment by hoanghun** [comment]
Musíme o víkendu udělat celkovej ten plán, podle toho pak uděláme diagram. Tak házejte nápady, hlavně tomu musíte věřit!! :octocat:

**Comment by hoanghun** [comment]
Já to vidím zatím tak, že cca 20 - 30 hodin každý na technologie, samotná implementace GUI taky zabere nějakých 30 hodin každýmu. Uvidíme, jak to půjde s tím QT a BT, jestli to prokopnem teda spolu nebo to vůbec nepůjde. 5 hodin každej nějaký to testování, atd .. napíšem to pak do WIKI asi

**Comment by simeckol** [comment]
to zní dobře, snad ty časy budou stačit, možná bychom si měli udělat nějakou časovou rezervu? :)

**Comment by simeckol** [comment]
btw jaký máme ten keoficient?
